## Filament Image Meta (asignua/filament-image-meta)

- Per-file alt text, "decorative" flag, caption, title and focal point for core Filament uploads. Wrap the upload: `ImageMetaUpload::make(FileUpload::make('photo')->image()->disk('public'), locales: ['en', 'uk'], caption: true, focalPoint: true, requireAlt: true)`. It returns a state-less `Group` holding the upload and a panel as SIBLINGS; put the result in `->components([...])`, never call methods of the upload on it. Arguments: `alt`, `decorative`, `caption`, `title`, `focalPoint` (bools), `locales` (empty = one language-less value), `requireAlt` (bool|Closure), `requiredLocales` (default: the first locale), `statePath` (sibling attribute name).
- Plain `FileUpload`: the details go to a sibling attribute `{name}_meta` (default; config `image-meta.meta_suffix`), keyed by stored file path. The model needs a JSON column for it and an `array` cast, and the save code must write it (a model with `$guarded = ['*']` needs the repository/DTO to assign `photo_meta`, otherwise the value is dropped silently).
- `SpatieMediaLibraryFileUpload`: nothing to add to the model. The details are written to each media item's `custom_properties` after the upload's own relationship save; names come from config `image-meta.media_properties` (defaults `alt`, `alt_decorative`, `caption`, `title`, `focal_point`).
- Read: `ImageMeta::for($model, 'photo')` (a column, or a media collection name when the model has no such column), `ImageMeta::allFor($model, 'gallery')` (path => meta), `ImageMeta::forMedia($media)`. `alt($locale)` is null when missing or decorative; `altAttribute($locale)` is the exact `alt` value: text, or `''` for decorative AND for undescribed images. There is no fallback to the file name and none between languages unless config `image-meta.fallback_locale` is set.
- Render with `<x-image-meta::img :src="$url" :meta="$meta" :locale="app()->getLocale()" class="object-cover" />` (or `<x-image-meta::figure>` for a caption). A focal point becomes `object-position`; it only has an effect together with `object-fit: cover`.
- Do not mark an image decorative to silence the `requireAlt` rule when it carries information. Decorative means the page loses nothing without it.
- The focal-point picker is an Alpine component (`resources/dist/focal-point.js`) registered with `FilamentAsset`; run `php artisan filament:assets` after installing.
